server:
  servlet:
    context-path: /booking

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: bookingusr
    password: bookingpwd

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

app:
  token:
    secret: CJxD7RA0InBYKIAyyq0LdgyqUFS4vXNkntiGvnjNe2Nkpzfe1PGdyISMDfMmxtxFc5yE7zBOjLBA/kKdoLEd0Q==
    issuer: org.mw.mwws
    expiration:
      access: 5
      refresh: 1500
    role:
      key: rol
    type:
      key: typ

  redis:
    user_e:
      key_prefix: "user:"
      key_ttl: 15
